version: "3"

services:
  admin-panel:
    build:
      dockerfile: admin_panel/Dockerfile
    restart: always
    container_name: admin-panel-notification
    volumes:
      - static_value:/code/app/static_files/
      - media_value:/code/app/media/
    env_file:
      - ./admin_panel/.env
