@startuml
skinparam componentStyle uml2
actor Пользователь

node api_database {
    database mongodb
}

node message_broker {
    database RabbitMQ
}

node auth_service {
    database Flask
}

node api_service {
    database FastAPI
}

node admin_panel{
    database Django
}

node Database{
    database Postgresql
}

node Worker{
    database notifications_history
}

node Events {
    database Cron
    database Scheduler

}

Пользователь -down----> admin_panel
Пользователь -down----> api_service
api_service -down--> api_database
api_service -right---> message_broker
api_database -up--> api_service

Django -right-> Postgresql

@enduml
