# Generated by Django 4.0.5 on 2022-07-05 11:21

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок шаблона рассылки')),
                ('type', models.CharField(choices=[('welcome', 'Письмо новому пользователю о новинках'), ('monthly', 'Ежемесячная рассылка'), ('personal', 'Персональная подборка')], max_length=50, verbose_name='Тип рассылки')),
                ('text', django_quill.fields.QuillField(verbose_name='Сообщение пользователю')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Templates',
                'db_table': 'notification_templates',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название задачи')),
                ('status', models.CharField(choices=[('send', 'Поставить на отправку'), ('letter_sent', 'Письма отправлены')], max_length=50, verbose_name='Статус рассылки')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.templates')),
            ],
            options={
                'verbose_name_plural': 'Tasks',
                'db_table': 'mailing_list_tasks',
            },
        ),
    ]
